package com.dcw.app.rating.db.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table cache.
 */
public class Cache {

    private Integer groupId;
    private String key;
    private String value;
    private Long expireTime;

    // KEEP FIELDS - put your custom fields here
    /** 缓存类型 */
    public int type = -1;

    /** 内存缓存 */
    public final static int CACHE_FROM_MEMORY = 0;

    /** 数据库缓存 */
    public final static int CACHE_FROM_DATABASE = 1;
    // KEEP FIELDS END

    public Cache() {
    }

    public Cache(String key) {
        this.key = key;
    }

    public Cache(Integer groupId, String key, String value, Long expireTime) {
        this.groupId = groupId;
        this.key = key;
        this.value = value;
        this.expireTime = expireTime;
    }

    public Integer getGroupId() {
        return groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Long getExpireTime() {
        return expireTime;
    }

    public void setExpireTime(Long expireTime) {
        this.expireTime = expireTime;
    }

    // KEEP METHODS - put your custom methods here
    public Cache(String value, long expireTime) {
        this.value = value;
        this.expireTime = expireTime;
    }

    public Cache(String key, String value, long expireTime) {
        this.key = key;
        this.value = value;
        this.expireTime = expireTime;
    }

    public Cache(String value, long expireTime, int type) {
        this.value = value;
        this.expireTime = expireTime;
        this.type = type;
    }

    public Cache(int groupId, String value, long expireTime, int type) {
        this.groupId = groupId;
        this.value = value;
        this.expireTime = expireTime;
        this.type = type;
    }
    // KEEP METHODS END

}
